name: unity-test

on:
  push:
    branches:
      - develop
    tags:
      - "!*"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  unity-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          # - path/to/your/project
          - .
        unityVersion:
          - 2020.1.14f1
        targetPlatform:
          # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          # - StandaloneWindows # Build a Windows standalone.
          # - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          # - iOS # Build an iOS player.
          # - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
          # - WSAPlayer # Build an Windows Store Apps player.
          # - PS4 # Build a PS4 Standalone.
          # - XboxOne # Build a Xbox One Standalone.
          # - tvOS # Build to Apple's tvOS platform.
          # - Switch # Build a Nintendo Switch player.

    steps:
      # Activate Unity Editor
      - name: Activate Unity Editor
        id: activation
        run: |
          git clone ${{ env.ULF_REPO }} .ulfs
          ULF_FILE=.ulfs/Unity_v${{ matrix.unityVersion }}.ulf
          UNITY_LICENSE=`cat $ULF_FILE | sed 's/^ *//' | tr -d '\n'`
          echo "UNITY_LICENSE=$UNITY_LICENSE" >> $GITHUB_ENV
        env:
          ULF_REPO: ${{ secrets.ULF_REPO }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-

      # - uses: webbertakken/unity-builder@v2.0-aplha-5
      #   with:
      #     projectPath: ${{ matrix.projectPath }}
      #     unityVersion: ${{ matrix.unityVersion }}
      #     targetPlatform: ${{ matrix.targetPlatform }}

      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: build

      - uses: webbertakken/unity-test-runner@7d26e264b92f726b5f8a207c10a96e0ba608a736
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          customParameters: "-enableCodeCoverage"

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          path: |
            artifacts/**/TestResults-*.xml
            CodeCoverage/**/TestCoverageResults_*.xml
